# Generated by Django 3.0.3 on 2020-06-21 12:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='facts',
            field=ckeditor.fields.RichTextField(default=True),
        ),
    ]
