# Generated by Django 3.0.3 on 2020-06-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
